project_name: pulsex-server
builds:
  - main: ./cmd/pulsex-server
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: pulsex-server
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "arm64" }}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
      - gomips: hardfloat
      - goamd64: v4
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - "none*"
changelog:
  skip: true
gitlab_urls:
  use_package_registry: true
  use_job_token: true
checksum:
  extra_files:
    - glob: ./build/MacOS.zip
release:
  extra_files:
    - glob: ./build/MacOS.zip
